version: '{build}'
os: Visual Studio 2017
configuration: Debug
environment:	
  COVERALLS_REPO_TOKEN:	Zj48R8Ur58rHyL9qmvTLgnN71iwWcWBZ4
skip_branch_with_pr: true
build_script:
- ps: >-
    ./Build.ps1

    nuget pack nuspec/Nito.Comparers.nuspec

    nuget pack nuspec/Comparers.nuspec

    nuget pack nuspec/Comparers.Ix.nuspec

    nuget pack nuspec/Comparers.Rx.nuspec
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '*.nupkg'
  - path: 'src\**\*.nupkg'
    name: NuGet Packages
  - path: 'src\**\*.snupkg'
    name: NuGet Symbol Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    APPVEYOR_REPO_TAG: true
